#A Local Database Of LocalDB Basic On Properties
#Wed Mar 11 21:46:50 CST 2026
APIKeySiliconFlow=65$\!(4f9(t^\!Q854Q5h\!t95Q75hEO(R-7RhZ(NN7h^h-NP7O8)y
APIUrlTextToImageSiliconFlow=https\://api.siliconflow.cn/v1/images/generations
APIUrlTextToTextSiliconFlow=https\://api.siliconflow.cn/v1/chat/completions
AutoCheckRenew=false
AutoDownloadRenew=false
AutoLaunch=false
ConfigConfigFileName=Config.properties
ConfigConfigFilePath=D\:\\Work\\produce\\work\\DailyPaper
ConnectTimeout=60
CurrentDateFormat=[yyyy.MM.dd-HH\:mm\:ss]
DailyPaperDownloadFileIsOpen=true
DailyPaperDownloadFileNameWindows=DailyPaper.exe
DailyPaperDownloadFilePath=D\:\\Work\\produce\\work\\DailyPaper
DailyPaperDownloadUrlWindows=https\://github.com/BProbie/DailyPaper/raw/refs/heads/master/DailyPaper.exe
DailyPaperRenewFileNameWindows=Renew.exe
DailyPaperRenewFilePath=D\:\\Work\\produce\\work\\DailyPaper
DailyPaperStageHeight=600
DailyPaperStageWidth=1200
ImageCount=1
ImageFileName=Image.png
ImageSize=1024x640
KolorsAPIModelSiliconFlow=Kwai-Kolors/Kolors
LiveImageConfigFileName=LiveImage.config
LiveImageConfigFilePath=D\:\\Work\\produce\\work\\DailyPaper\\LiveImage
LiveImageWallpaperFileName=LiveImage
LiveImageWallpaperFilePath=D\:\\Work\\produce\\work\\DailyPaper
LogConfigFileName=Log.2026-3-11.txt
LogConfigFilePath=D\:\\Work\\produce\\work\\DailyPaper
Qwen3_8BAPIModelSiliconFlow=Qwen/Qwen3-8B
ReadTimeout=180
RenewConfigFileName=Renew.properties
RenewConfigFilePath=D\:\\Work\\produce\\work\\DailyPaper
RenewConfigFileUrl=https\://raw.githubusercontent.com/BProbie/DailyPaper/refs/heads/master/Renew.properties
RootPath=D\:\\Work\\produce\\work\\DailyPaper
SplitMark=\ 
TempConfigFileName=Temp.properties
TempConfigFilePath=D\:\\Work\\produce\\work\\DailyPaper
WriteTimeout=60
